function(format_doxygen_input out_var)
    set(_log_level STATUS)
    message(${_log_level} "format_doxygen_input for ${out_var}")

    math(EXPR _itr_max "${ARGC}-1" OUTPUT_FORMAT DECIMAL)
    set(_result)

    foreach(_index RANGE 1 ${_itr_max})
        foreach(_src_list ${ARGV${_index}})
            message(${_log_level} "  Checking in list ${_src_list}")
            foreach(_src ${_src_list})
                message(${_log_level} "    Checking ${_src}")
                set(_result "${_result} \\\n  ${_src}")
            endforeach()
        endforeach()
    endforeach()
    set(${out_var} ${_result} PARENT_SCOPE)
endfunction()
